SOURCES = [
 {'market':'Meridian','grade':'A+','mode':'automated-report','url':'https://data.meridiancity.org/community-development/building/construction-reports/','use':'Weekly construction reports'},
 {'market':'Nampa','grade':'A+','mode':'automated-report','url':'https://www.cityofnampa.us/427/Permit-Reports','use':'Weekly permit activity and commercial review status'},
 {'market':"Coeur d'Alene",'grade':'A+','mode':'automated-pdf','url':'https://building.cdaid.org/Reports/IssuedPermitsLastWeek','use':'Direct weekly issued permits'},
 {'market':'Kootenai County','grade':'A+','mode':'automated-pdf','url':'https://kcgov.us/Archive/44','use':'Weekly county building permit archive'},
 {'market':'Boise','grade':'A+ early lead','mode':'automated-gis','url':'https://services1.arcgis.com/WHM6qC35aMtyAAlN/ArcGIS/rest/services/Development_Tracker_Open_Data/FeatureServer/0','use':'Daily active planning/development tracker; early project leads before building permit issuance'},
 {'market':'Eagle','grade':'A+','mode':'automated-portal','url':'https://portal.iworq.net/EAGLE/permits/600','use':'Rolling public permit records; detail-page crawl supports client-rendered listings and shared classifier suppresses trades'},
 {'market':'Eagle Laserfiche','grade':'A','mode':'backfill-report','url':'https://lf.cityofeagle.org/WebLink/?dbid=0&repo=CityofEagle','use':'Official weekly permit report repository for historical/backfill research'},
 {'market':'Canyon County','grade':'A+ early lead','mode':'automated-gis','url':'https://maps.canyonco.org/arcgisserver/rest/services/DSD/Building_Permits_NEW_2023/FeatureServer/1','use':'Current active building-permit applications; received date, status, approval state, project, contractor and valuation'},
 {'market':'Canyon County Planning','grade':'A+ early lead','mode':'planning','url':'https://www.canyoncounty.id.gov/elected-officials/commissioners/development-services/dsd-gis/','use':'Planning & zoning application tracker'},
 {'market':'Caldwell','grade':'A+ candidate','mode':'discovery-portal','url':'https://www2.citizenserve.com/Portal/PortalController?Action=showSearchPage&ctzPagePrefix=Portal_&type=Permit&installationID=263','use':'Official live Citizenserve permit search; fail-closed discovery of unattended search semantics'},
 {'market':'Caldwell Reports','grade':'A backfill','mode':'rep-report','url':'https://www.cityofcaldwell.org/Departments/Community-Development/Building-Safety-Division/Building-Bulletins-Reports','use':'Official monthly building reports for fallback and backfill'},
 {'market':'Star','grade':'B','mode':'rep-research','url':'https://www.staridaho.org/departments/building/','use':'Search existing permits'},
 {'market':'Middleton','grade':'B','mode':'rep-research','url':'https://www4.citizenserve.com/Portal/PortalController?Action=showHomePage&ctzPagePrefix=Portal_&installationID=242&original_contactID=0&original_iid=0','use':'Building permit portal'},
 {'market':'Post Falls','grade':'A','mode':'rep-report','url':'https://www.postfalls.gov/175/Building','use':'Monthly building reports'},
 {'market':'Post Falls OpenGov','grade':'B+','mode':'rep-research','url':'https://postfallsid.portal.opengov.com/','use':'Building/planning/engineering project research'},
 {'market':'Twin Falls','grade':'A','mode':'rep-report','url':'https://www.tfid.org/214/Building-Permit-Information','use':'Dashboard, current commercial permits and monthly lists'},
 {'market':'Pocatello','grade':'B+','mode':'rep-research','url':'https://poca.csqrcloud.com/community-etrakit/','use':'Permit/project/contractor/map search'},
 {'market':'Idaho Falls','grade':'B','mode':'rep-research','url':'https://cw.idahofalls.gov/','use':'Cityworks permit/project research'},
]
